fars_read <- function(filename) {
  #' Import file
  #'
  #' This is a simple function importing a file with a given
  #' filename. The function throughs an error if the file
  #' is not present. If present the content of the table is imported
  #' by \code{read_csv()} of the package readr and further converted into
  #' tibble data frame by tbl_df, a function of dplyr package.
  #'
  #' @param filename A character string giving the exact filename
  #' including the file extension.
  #' 
  #' @importFrom dplyr
  #'
  #' @return This function returns a tibble data frame, generated by \code{tbl_df()}
  #' of the package dplyr
  #'
  #' @examples
  #' fars_read('temp.csv')
  #' fars_read(filename = 'temp.csv')
  #' 
  #' @export
  if (!file.exists(filename))
    stop("file '", filename, "' does not exist")
  data <- suppressMessages({
    readr::read_csv(filename, progress = FALSE)
  })
  dplyr::tbl_df(data)
}

make_filename <- function(year) {
  #' Create a filename
  #'
  #' This is a simple function adding a choosen year to
  #' 'accident_%d.csv.bz2 and prints it.
  #'
  #' @param year A character string of the year that should be included
  #' in the filename
  #'
  #' @examples
  #' make_filename(2017)
  #' make_filename('2017')
  #' make_filename(year = '2017')
  #'
  #' @export
  year <- as.integer(year)
  sprintf("accident_%d.csv.bz2", year)
}


fars_read_years <- function(years) {
  #' Import and rearrangement of input files by year
  #' 
  #' This functions imports files based on the stated year using the function
  #' \code{make_filename()} and \code{fars_read()}.
  #' The application dplyr provides the rearrangement of input file by
  #' year and month - \code{dplyr::mutate}} and \code{dplyr::select}. 
  #' The function throws a warning in case the data for one or several of the
  #' requested years is not available. 
  #' 
  #' @param years A single or collection of years in character format, if invalid
  #' warning is thrown
  #'
  #' @importFrom dplyr
  #' 
  #' @examples
  #' fars_read_years()
  #' fars_read_years(2013)
  #' fars_read_years(years = c('2013', '2017'))
  #' fars_read_years(years = c('2013'))
  #' 
  #' @return Function returns a list containing an entry per year summarising 
  #' a tibble data frame showing months and years
  #' 
  #' @export
  lapply(years, function(year) {
    file <- make_filename(year)
    tryCatch({
      dat <- fars_read(file)
      dplyr::mutate(dat, year = year) %>% 
        dplyr::select(MONTH, year)
    }, error = function(e) {
      warning("invalid year: ", year)
      return(NULL)
    })
  })
}

fars_summarize_years <- function(years) {
  #' Create a summary per year
  #' 
  #' This functions creates a summary per requested year
  #' of accidents per month and stores it in a tibble per year
  #' stating per month.
  #' The function uses \code{dplyr::bind_rows()}, \code{dplyr::group_by} and 
  #' \code{dplyr::summarise} as well as \code{tidyr::spread}.
  #' 
  #' @param years A single or vector or year
  #' 
  #' @importFrom dplyr tidyr
  #' 
  #' @return A tibble data frame stating per requested year the number of 
  #' accidents per each month
  #' 
  #' @examples
  #' fars_summarize_years(years = '2013')
  #' fars_summarize_years(years = c(2013,2017))
  #' fars_summarize_years(c(2013,2017))
  #' 
  #' @export
  dat_list <- fars_read_years(years)
  dplyr::bind_rows(dat_list) %>% 
    dplyr::group_by(year, MONTH) %>% 
    dplyr::summarize(n = n()) %>%
    tidyr::spread(year, n)
}

fars_map_state <- function(state.num, year) {
  #' Plot a map of each state showing accidents per year
  #' 
  #' This complex functions reads data of a specific year 
  #' stating the number of accidents.
  #' The incorporated functions \code{make_filename()}, \code{fars_read()} facilitate
  #' the import of the data.
  #' The imported functions \code{dplyr::filter}, \code{maps::map} and 
  #' \code{graphics::point provide} the plot of each state.
  #' In case of invalid state numbers functions exit and states an error message. 
  #' If no data is available to plot function prints a message, stating so.
  #' 
  #' @param state.num Number of the state, if not valid function stops and state 'invalid
  #' STATE number'
  #' 
  #' @param year Single number of year 
  #' 
  #' @importFrom maps, dplyr, graphics,
  #' 
  #' @return A map plotting a point per accident per state
  #' 
  #' @examples
  #' fars_map_state(state.num = 1, year = 2013)
  #' fars_map_state(1, 2013)
  #' 
  #' @export
  filename <- make_filename(year)
  data <- fars_read(filename)
  state.num <- as.integer(state.num)
  
  if (!(state.num %in% unique(data$STATE)))
    stop("invalid STATE number: ", state.num)
  data.sub <- dplyr::filter(data, STATE == state.num)
  if (nrow(data.sub) == 0L) {
    message("no accidents to plot")
    return(invisible(NULL))
  }
  is.na(data.sub$LONGITUD) <- data.sub$LONGITUD > 900
  is.na(data.sub$LATITUDE) <- data.sub$LATITUDE > 90
  with(data.sub, {
    maps::map("state", ylim = range(LATITUDE, na.rm = TRUE),
      xlim = range(LONGITUD, na.rm = TRUE))
    graphics::points(LONGITUD, LATITUDE, pch = 46)
  })
}
